#' phiper
#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @useDynLib phiper, .registration = TRUE
#' @importFrom Rcpp evalCpp
#' @importFrom RcppParallel setThreadOptions
#' @importFrom dplyr %>%
## usethis namespace: end
NULL

# There is a note for not-declared global variables in R CMD CHECK. This is a
# little bit tricky when using dplyr to manipulate the data, as you use the
# unquoted names of the variables to access the columns in the data. R CMD CHECK
# sees it as a global variable and cries, that you use it, but haven't defined
# it. It is a pretty well known bug, i bypassed it a little bit differently in
# vecmatch, but actually defining all the variables as global will also do the
# trick + you have all the vars in one place.
utils::globalVariables(c(
  "%>%",
  ".",
  "..keep_cols",
  ".env",
  ".exist",
  ".x",
  ":=",
  "H_ln",
  "N",
  "N1",
  "N2",
  "N_1",
  "N_2",
  "N_paired",
  "PAIRS",
  "POOL",
  "T_obs",
  "T_obs_stand",
  "Z_from_p",
  "b",
  "category",
  "category_rank_bh",
  "category_rank_wbh",
  "category_use",
  "cohort",
  "d1",
  "d2",
  "delta",
  "delta_jit",
  "design",
  "distance",
  "dummy",
  "example",
  "feature",
  "frac_delta_pos",
  "frac_delta_pos_w",
  "group",
  "group1",
  "group2",
  "group_col",
  "group_value",
  "group_value_1",
  "group_value_2",
  "idx_hits_g1",
  "idx_hits_g2",
  "k",
  "k_levels",
  "log2ratio",
  "m_eff",
  "m_r",
  "max_delta",
  "n",
  "n1",
  "n1_paired",
  "n1_tot",
  "n1_val",
  "n2",
  "n2_paired",
  "n2_tot",
  "n2_val",
  "n_dups",
  "n_peptides",
  "n_peptides_used",
  "n_pos",
  "n_present",
  "n_present_1",
  "n_present_2",
  "n_subjects_paired",
  "nlog10p",
  "p1_val",
  "p2_val",
  "padj_bh",
  "p_adj_rank",
  "p_adj_rank_wbh",
  "p_perm",
  "p_raw",
  "passed_rank_bh",
  "passed_rank_wbh",
  "pct1val",
  "pct2val",
  "pep_key",
  "peptide_id",
  "percent1",
  "percent2",
  "percent_1",
  "percent_2",
  "pooled",
  "pooled_jit",
  "present",
  "present_1",
  "present_2",
  "prop",
  "prop1",
  "prop1_eps",
  "prop1_paired",
  "prop2",
  "prop2_eps",
  "prop2_paired",
  "prop_1",
  "prop_2",
  "rank_val",
  "ratio",
  "richness",
  "sample_id",
  "score",
  "shannon",
  "simpson",
  "subject_id",
  "time_cont",
  "v",
  "view",
  "x",
  "y",
  "T_null_mean",
  "T_null_sd"
))
